# Generated by Django 2.1.2 on 2018-12-07 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20181207_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='participants',
        ),
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
