version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/code
    ports: 
      - "80:8000"
    depends_on: 
      - db